### ISSUE TITLE
启动服务器不能设置debug模式，而且登陆的ObjectID会抛异常。数据库和redis都已启动

### ISSUE THREAD

**Issue by DeloDuan** [xymeng2017/friendofpomelo#2]
[2017-06-23 10:40:14.352] [INFO] console - connected
[2017-06-23 10:40:14.354] [ERROR] pomelo-rpc - \Dev\project-server\test-servers\friendofpomelo\game-server\node_modules\pomelo-rpc\lib\rpc-server\acceptors\mqtt-acceptor.js: [mqtt-acceptor] process rpc message error Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
    at new ObjectID (D:\Dev\project-server\test-servers\friendofpomelo\game-server\node_modules\bson\lib\bson\objectid.js:50:11)
    at ObjectID (D:\Dev\project-server\test-servers\friendofpomelo\game-server\node_modules\bson\lib\bson\objectid.js:31:42)
    at Remote.auth (D:\Dev\project-server\test-servers\friendofpomelo\game-server\app\servers\auth\remote\authRemote.js:89:27)
    at Dispatcher.pro.route (D:\Dev\project-server\test-servers\friendofpomelo\game-server\node_modules\pomelo-rpc\lib\rpc-server\dispatcher.js:52:10)
    at Acceptor.cb (D:\Dev\project-server\test-servers\friendofpomelo\game-server\node_modules\pomelo-rpc\lib\rpc-server\gateway.js:22:16)
    at processMsg (D:\Dev\project-server\test-servers\friendofpomelo\game-server\node_modules\pomelo-rpc\lib\rpc-server\acceptors\mqtt-acceptor.js:138:12)
    at Connection.<anonymous> (D:\Dev\project-server\test-servers\friendofpomelo\game-server\node_modules\pomelo-rpc\lib\rpc-server\acceptors\mqtt-acceptor.js:62:11)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)

**Comment by xymeng2017** [comment]
我的锅我的锅，我把_id默认赋值为null了，默认应该是undefined才对，已经改了。
